### ISSUE TITLE
Compatability with godot 3.2.2

### ISSUE THREAD

**Issue by MossFrog** [Shfty/qodot-plugin#106]
I cannot seem to instance a Qodot node in Godot version 3.2.2 , i can manually attach the map script to a spatial but when i attach a map file to it the map does not load within the editor.

**Comment by raphipod** [comment]
Have you seen the "Full Build"-option on top of the 3D-View coming up? Press it, and the map should load.

**Comment by Shfty** [comment]
@MossFrog Are you seeing any errors in the Output tab? If the map doesn't build when you click on the Full Build button, that suggests the native libraries haven't loaded.

One possible cause of this is trying to use QodotMap before enabling Qodot in Project Settings - there's a download process that gets kicked off to fetch dependencies from GitHub.

**Comment by MossFrog** [comment]
Yeah that was the issue, i forgot to enable the addon from the project settings, all is well now. Im curious as to if it is possible to increase the number of vertices from the exported map file?

**Comment by Shfty** [comment]
There shouldn't be any limits Qodot-side in terms of how complex imported geo should be, and I'm not aware of TrenchBroom or the map format itself imposing anything like that. Certain massive map files (~40MB+) may cause VisualServer to crash due to their complexity, but that's more a Godot core issue than anything.

If I've missed the point and the above doesn't address your question, feel free to open a new issue with more specifics and I'll take a look.
