### ISSUE TITLE
Load maps when the game is compiled and running

### ISSUE THREAD

**Issue by TomMars** [Shfty/qodot-plugin#114]
It is possible to open a .map file when you compiled your game and you running it?
I want to let users create custom maps like in Source's games.

**Comment by Shfty** [comment]
Yes, Qodot can load map files at runtime:
[Qodot Wiki - Usage / Using Qodot at runtime](https://github.com/Shfty/qodot-plugin/wiki/2.-Usage#using-qodot-at-runtime)

There are some limitations around custom resources to be aware of - since things like textures (both loose and WAD-based), models and materials need an editor-side import process before they can be used, maps loaded at runtime can only use resources that already exist inside your built project.
