### ISSUE TITLE
Godot UV and Trenchbroom texture scale missmatch

### ISSUE THREAD

**Issue by kelo221** [Shfty/qodot-plugin#133]
The UV scale must be set extremely low to make the textures reasonably sized. Is this a bug or am I missing something?
I'd to make the tiles not leave a small gap, but Godot does not allow diving the UV to the required accuracy.
![image](https://user-images.githubusercontent.com/61495413/127800956-745e9173-316c-41fb-9df7-bb1eb83363e0.png)
![image](https://user-images.githubusercontent.com/61495413/127800980-8751c062-c0d2-47b9-b3d6-0cc265db622e.png)
![image](https://user-images.githubusercontent.com/61495413/127801091-f0dffa1d-f9c2-4f41-99c4-53e2c60fc54a.png)
![image](https://user-images.githubusercontent.com/61495413/127801106-cfb41765-6863-47de-8711-60f5654cc11e.png)

**Comment by Shfty** [comment]
Don't use SpatialMaterial's UV scale for this. That applies inside the shader, and your UVs should be 'correct' long before they get to the GPU. Scaling is also a bad way to do this, since it's multiplicative and therefore painful to make accurate at extreme values.

The idiomatic way to align textures is to do it inside your map editor, as its world units correspond to texel units and thus allow for the pixel-perfect alignment you're looking for.

You can use the Inverse Scale Factor on QodotMap to scale the incoming map geometry on build, so you can figure out an appropriate texel density using TB units, and then alter the physical size to best suit your Godot-side implementation.
