### ISSUE TITLE
Default inverse scale factor

### ISSUE THREAD

**Issue by fossegutten** [Shfty/qodot-plugin#75]
Hi, love your addon!
Just had a thought about the scale factor. In the wiki it says Quake units are in inches, and set the scale factor to 16 to match Godot units (meters).

1 meter divided by 1 inch (0,0254 meters) is about 40. Should the value maybe be changed to 40?

**Comment by donovan1212** [comment]
The "Unit" in quake does not actually correspond to a value

**Comment by Shfty** [comment]
Quake units are only very loosely considered to be in inches- Carmack mentioned that's what they were based on at one point, but in practice the actual scale of entities and architecture in Quake doesn't conform to a real-world metric.

Take Ranger as an example - in Quake he's 56qu high, which translates to 1.4224 meters if you assume inches as the metric. By comparison, standard-size doors are 128 * 128qu, which shakes out to 3.2512 * 3.2512 meters when converted from inches.

So by that measure, Quake is a game about a tiny man running around in massive environments. It doesn't really map to reality.

Thus, the default value is set to 16 so that Quake architecture and entities will covert across 'well enough' to be correct in terms of Godot's physics system, which uses metric as its baseline.

You can of course change it on a project-by-project basis if you decide to map at a bigger or smaller scale than in Quake.
