### ISSUE TITLE
GIprobe artifacts when adding brush to a group

### ISSUE THREAD

**Issue by fossegutten** [Shfty/qodot-plugin#87]
Edit: Using Qodot 1.6.2

Steps to reproduce:

1. Create a brush in trenchbroom. 
2. Create another brush. Add it to a group with random name. ( only this one will not be baked properly)
3. Create another brush. Create a brush entity. Then add it to a group with random name afterwards. (Adding to a group if it is a brush entity works fine).
4. Import map with Qodot.
5. Create a GI probe, and bake it.

Artifact to the left. Normal to the right.
![Godot_v3 2-stable_win64_aC2pfArUj8](https://user-images.githubusercontent.com/15088582/75272927-1d6a3c80-57ff-11ea-868c-eb4d41b01861.png)

**Comment by Shfty** [comment]
This is due to the func_groups TrenchBroom piggybacks on for its internal grouping functionality aren't recognized by the 1.6.x FGD, and thus come through as non-static entities.

This behavior is more controllable in the latest commits to `master`, but for now the solutions are:
A. Make any brushes inside TB groups entities, and set `_shadow` if their classnames aren't set to merge with worldspawn
B. Add a `func_group` FGD entry and set it to merge worldspawn. This will break the nested group functionality for now (fixed in master)
C. Avoid using TrenchBroom groups
