### ISSUE TITLE
When I  try to export to Windows from Linux breaks because missing files

### ISSUE THREAD

**Issue by sergicollado** [Shfty/qodot-plugin#96]
The report:
 core/os/dir_access.cpp:288 - Failed to open res://addons/qodot/bin/win64/libmap.dll
 editor/project_export.cpp:977 - Failed to export the project for platform 'Windows Desktop'.
 core/os/dir_access.cpp:288 - Failed to open res://addons/qodot/bin/win64/libqodot.dll
 editor/project_export.cpp:977 - Failed to export the project for platform 'Windows Desktop'.

**Comment by Shfty** [comment]
This is already documented at https://github.com/Shfty/qodot-plugin/wiki/9.-Project-Export

TL;DR you can safely exclude the parts of Qodot that throw these errors via the project export settings, provided that you're not using it to load maps at runtime. Otherwise, you'll need to download and ship the windows libs with your project.
